baseURL: http://localhost
projectName: finary
scenarios:
  - name: Consulter les titres
    path: ./scenarios/consult_index.js
  - name: Consulter un article
    path: ./scenarios/consult_expenses.js
containers:
  - finary-static_hosting-1
  - finary-backend-1

